


void delay (int segundos) {
	
	int t;
	
	t = clock ();
	while (clock() < t + segundos * 125){
			
	};
	
};

void lapagod () {
	
	printf("**********************************/*///(((#%%%%(**********************************\n");
	printf("*************************.#%%(/,......,,,,,,......,*/(%%&/************************\n");
	printf("**********************,... .... ..........  ........,,*(#%%&&%%*******************\n");
	delay(1);
	printf("***********************.. .... ...........   ........,,../#&&&&&%%***************\n");
	printf("*********************,.......   ...... .......   ... .,...,(&&&&&&&%%************\n");
	printf("********************,..... ..  ................. ........,,.,(%%%%&&&&&&(*********\n");
	delay(1);
	printf("*******************,. ...  ....,/**,,,,,,.,,,,,,,............,*%%%%%%%%%%%%%%%%&%%*******\n");
	printf("******************,...... ..,/#%%%%#(/****/(((###%%##(/,,.  ....,,(%%%%%%%%%%%%%%%%%%%%#*****\n");
	printf("***********,*****,...... .*(%%%%&&&&&%%#########%%%%%%%%&&%%%%#(,......./%%%%%%%%%%%%%%%%%%%%%%%%****\n");
	delay(1);
	printf("***///////*,,****,....,.../#%%&&&&&&%%%%%%########%%%%&&&&&&%%(,......(%%%%%%%%%%%%%%%%%%%%%%%%%%#**\n");
	printf("***********,,*****,...,..,(%%&&&&&&&&%%%%%%%%%%%%%%%%%%%%%%%%&&&&&&%%(*,..../%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%*\n");
	printf("***********,,,***,,....../%%%%%%%%%%##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%&&&&&&%%(*,....*%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	delay(1);
	printf("/*//*******,,,***,....  *#%%%%%%####(((((#%%&%%%%%%#(////((##%%#*.....(%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf("//////(/***,.,****////**(((##/*/*.**/((##(%%#(/////(#%%###, . .,#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf("////////***,.,,****/((*/%%#%%%%%%#%%%%(////((((((((/*****/,(#(***//(%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	delay(1);
	printf("/*//////***,.,,,****(#(#%%%%&&%%%%###((#####%%%%%%###((((%%%%%%%%&%%(/((#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf("******,****,.,,,,**,*(%%%%%%&&&&&%%%%##(###%%%%%%%%&%%%%#####%%%%&&&&((%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf("***********,.,,,,,**,*#%%%%&&&&&%%#(/(%%%%&&%%%%%%%%%%%%#/(#%%%%&&&&&&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	delay(1);
	printf("*,***,*****,..,,,,,,,,,/&&&&&%%%%((#%%%%#%%%%%%%%%%%%##%%#//(%%%%&&&%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf(",,**,******,..,,..   .  #&&&&%%(*.,,,,,*//*,,**/((#%%%%%%&&(,..,/##%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
	printf(",,,****,,,......   ...  *%%&&%%(*,*///#%%%%%%##(/*,,.,(%%%%&&(,.  .    ..,,,*/(#%%%%%%%%%%%%%%\n");
	delay(1);
	printf("........    .........   *%%%%%%&&%%%%%%%%%%%%#########%%#((#%%%%#,,,,,.     .. ..........,,*\n");
	printf(".......     . ........  .#%%%%%%%%%%&&&#((((((####%%%%%%%%%%%%/ ,,,,,..     .. ............\n");
	printf("@.    .       ........   *#%%%%%%#(%%&%%#/****/(%%&&%%#%%%%#..,,,....  .   ... .........@\n");
	delay(1);
	printf("@@*   ..       .......   .*#%%%%#*,*//*****/((/**(&#, .,,......     ..   .......@@\n");
	printf("@@@@......   ........... .,*#%%%%#/*.........,,,/%%#, ..,,,.......   .. .......*@@@\n");
	printf("@@@@@,....   ..............,*(%%%%%%%%%%#(***//(##%%%%*  ..,,.........   .........@@@@@\n");
	delay(1);
	printf("@@@@@@@...   ...........,,..,*/(#%%%%%%%%#%%%%%%%%%%#/,......,..........   .......@@@@@@@\n");
	printf("@@@@@@@@@*    ..........,.....,*/((##((((//,...............   .  ......@@@@@@@@@\n");
	printf("@@@@@@@@@@@@  .........   .,....,/////////*. ..,...........  ..  ...#@@@@@@@@@@@\n");
	delay(1);
	printf("@@@@@@@@@@@@@@@.........     .....,**///**,...  ........... ... .%%@@@@@@@@@@@@@@\n");
	printf("@@@@@@@@@@@@@@@@@@&.........  ..   ..,**,.... ............. .,@@@@@@@@@@@@@@@@@@\n");
	printf("@@@@@@@@@@@@@@@@@@@@@@@#..... ....   ........ ..........*@@@@@@@@@@@@@@@@@@@@@@@\n");
	printf("\n                      L A P A  P R O D U C T I O N S\n\n");
	

}

void loading () {
	
	
	printf ("Inicializando jogo.\n\n");
	delay(1);
	system("cls");
	printf ("Inicializando jogo..\n\n");
	delay(1);
	system("cls");
	printf ("Inicializando jogo...\n\n");
	system("cls");

	delay(3);
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X        O                                       X\n");
    printf ("X                                 o        O     X\n");
    printf ("X     O                                          X\n");
    printf ("X                   Carregando                   X\n");
    printf ("X         o      [              ]       o        X\n");
    printf ("X                                                X\n");
    printf ("X                         O                      X\n");
    printf ("X     O                              o       O   X\n");
    printf ("X                                                X\n");
    printf ("X                     o                          X\n");
    printf ("X         o                       O        o     X\n");
    printf ("X                O                               X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X                                o         O     X\n");
    printf ("X   O                                            X\n");
    printf ("X                                                X\n");
    printf ("X          o        Carregando          o        X\n");
    printf ("X                [XX            ]                X\n");
    printf ("X                         O                      X\n");
    printf ("X     O                             o        O   X\n");
    printf ("X                                                X\n");
    printf ("X                    o                           X\n");
    printf ("X        o                        O       o      X\n");
    printf ("X              O                                 X\n");
    printf ("X                                                X\n");
    printf ("X   o                                o           X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X    O                                           X\n");
    printf ("X                                                X\n");
    printf ("X         o              o               o       X\n");
    printf ("X                   Carregando                   X\n");
    printf ("X                [XXXX          ]                X\n");
    printf ("X    o                             o         O   X\n");
    printf ("X                                                X\n");
    printf ("X                    o                           X\n");
    printf ("X       O                        O        o      X\n");
    printf ("X              O                                 X\n");
    printf ("X                                                X\n");
    printf ("X    o                               o           X\n");
    printf ("X                        O                       X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X                                                X\n");
    printf ("X        o                o                o     X\n");
    printf ("X                                                X\n");
    printf ("X                   Carregando                   X\n");
    printf ("X    o           [XXXXXX        ]  o         O   X\n");
    printf ("X                                                X\n");
    printf ("X                                                X\n");
    printf ("X       O            o           O        o      X\n");
    printf ("X              O                                 X\n");
    printf ("X                                                X\n");
    printf ("X     o                              o           X\n");
    printf ("X                      O                         X\n");
    printf ("X          o                       O             X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X          o               o              o      X\n");
    printf ("X                                                X\n");
    printf ("X                                                X\n");
    printf ("X   o               Carregando      o        O   X\n");
    printf ("X                [XXXXXXXX      ]                X\n");
    printf ("X                                                X\n");
    printf ("X       O           o           O        o       X\n");
    printf ("X             O                                  X\n");
    printf ("X                                                X\n");
    printf ("X    o                                o          X\n");
    printf ("X                      O                         X\n");
    printf ("X          o                      O              X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X                                                X\n");
    printf ("X                                                X\n");
    printf ("X     o                            o        O    X\n");
    printf ("X                   Carregando                   X\n");
    printf ("X                [XXXXXXXXXX    ]                X\n");
    printf ("X     O              o                  o        X\n");
    printf ("X            O                  O                X\n");
    printf ("X                                                X\n");
    printf ("X     o                                o         X\n");
    printf ("X                      O                         X\n");
    printf ("X         o                      O               X\n");
    printf ("X                                         o      X\n");
    printf ("X             o                                  X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X                                                X\n");
    printf ("X      o                          o          O   X\n");
    printf ("X                  o                             X\n");
    printf ("X                   Carregando                   X\n");
    printf ("X    O           [XXXXXXXXXXXX  ]      o         X\n");
    printf ("X            O                  O                X\n");
    printf ("X                                                X\n");
    printf ("X    o                                  o        X\n");
    printf ("X                     O                          X\n");
    printf ("X          o                    O                X\n");
    printf ("X                                         o      X\n");
    printf ("X            o                                   X\n");
    printf ("X                       O                        X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(3);
	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X     o                          o          O    X\n");
    printf ("X                o                               X\n");
    printf ("X                            O                   X\n");
    printf ("X   O               Carregando        o          X\n");
    printf ("X           O    [XXXXXXXXXXXXXX]                X\n");
    printf ("X                                                X\n");
    printf ("X    o                                    o      X\n");
    printf ("X                     O       O                  X\n");
    printf ("X         o                                      X\n");
    printf ("X                                        o       X\n");
    printf ("X            o                                   X\n");
    printf ("X                      O                         X\n");
    printf ("X      O                               o         X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    delay(1);
};

void MenuPrincipal(){
	
	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
	printf ("X                         O                      X\n");
	printf ("X       O      o                  o         o    X\n");
	printf ("X                 B A T A L H A        O         X\n");
	printf ("X   o            L A P O N I C A                 X\n");
	printf ("X          O                                     X\n");
	printf ("X                                  o        O    X\n");
	printf ("X                  1-> Jogar                     X\n");
	printf ("X   O         o    2-> Tutorial          O       X\n");
	printf ("X                  3-> Jogadores    o            X\n");
	printf ("X           o      4-> Sair                      X\n");
	printf ("X                              O           O     X\n");
	printf ("X     O          O                     o         X\n");
	printf ("X                        o                       X\n");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
	printf ("->");
}

void MenuTutorial(){
	
	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
	printf ("X          o       |[Tutorial]|    o             X\n");
	printf ("X    O             X----------X            O     X\n");
	printf ("X                     O        o                 X\n");
	printf ("X          o                           o         X\n");
	printf ("X                                           o    X\n");
	printf ("X   o             1-Habilidades                  X\n");
	printf ("X         O       2-Jogabilidade          O      X\n");
	printf ("X                  3-Como Jogar                  X\n");
	printf ("X                4-Menu Principal          o     X\n");
	printf ("X   O     o                                      X\n");
	printf ("X                      o               O         X\n");
	printf ("X      o                                    o    X\n");
	printf ("X               O            o       o           X\n");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
	printf ("->");
}

void ListaHab(){
	
	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X            O           O              o        X\n");
	printf ("X                                           O    X\n");
	printf ("X   o        Toda habilidade só poderá           X\n");
	printf ("X           ser ativa com a tropa especial       X\n");
    printf ("X                      viva.                 O   X\n");
    printf ("X         o                                      X\n");
    printf ("X   O              o           O       o       o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X            O           O              o        X\n");
	printf ("X                                           O    X\n");
	printf ("X      Dash-> O jogador poderá fazer 3           X\n");
	printf ("X     movimentos na rodada com qualquer          X\n");
    printf ("X     guerreiro. Limite 1 por round.         O   X\n");
    printf ("X         o                                      X\n");
    printf ("X   O              o           O       o       o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X             |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X   o        O           O              o        X\n");
	printf ("X                                                X\n");
	printf ("X      Attack Boost-> O dano de ataque da        X\n");
	printf ("X     tropa especial é aumentada em 2 de dano    X\n");
	printf ("X     durante todo o jogo. Uso passivo, sem      X\n");
    printf ("X     necessidade de ativação.                   X\n");
    printf ("X   O              o           O               o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	 	system("pause");
    	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X                                           O    X\n");
	printf ("X      Barreira-> O guerreiro especial pode      X\n");
	printf ("X     criar uma barreira de 3x1 bloqueando       X\n");
	printf ("X     ataques inimigos em sua direção, após  o   X\n");
	printf ("X     o tiro o bloco atingido será destruido.    X\n");
	printf ("X O   Caso a barreira não seja destruida em      X\n");
	printf ("X     2 rounds, sera destruida por completo.     X\n");
    printf ("X                       o           o            X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X                                           O    X\n");
	printf ("X   o  Cura-> O guerreiro especial terá          X\n");
	printf ("X     capacidade de se curar 3 pontos de vida    X\n");
	printf ("X     e dos aliados que estiverem na area de     X\n");
	printf ("X O   3x3 originado dele. Limite 1 uso por       X\n");
    printf ("X     round.                            O        X\n");
    printf ("X   O              o           O               o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X            O           O              o        X\n");
	printf ("X                                           O    X\n");
	printf ("X      Freeze-> O jogador ganha a habilidade     X\n");
	printf ("X     de congelar 1 inimigo por 2 rounds,        X\n");
    printf ("X     com 70%% de chance de acerto. Limite    O   X\n");
    printf ("X     de 1 uso por round                         X\n");
    printf ("X   O              o           O       o       o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
   	printf ("X  o          |     [Tutorial]     |     o       X\n");
	printf ("X    O        |Lista de Habilidades|         O   X\n");
   	printf ("X             X--------------------X             X\n");
    printf ("X                                           O    X\n");
	printf ("X   o  HP Boost-> A vida da tropa especial é     X\n");
	printf ("X     aumentada para 20 de vida durante todo     X\n");
	printf ("X     o jogo. Uso passivo, sem necessidade de    X\n");
	printf ("X O   ativação.                                  X\n");
    printf ("X                                       O        X\n");
    printf ("X   O              o           O               o X\n");
    printf ("X                                                X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                                X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    	system("pause");
    	system("cls");

    	
}

void Jogabilidade(){
	
			system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X        O        | [Tutorial] |    O       o    X\n");
    printf ("X   o             |Jogabilidade|                 X\n");
    printf ("X      O          X------------X  o          O   X\n");
    printf ("X                                                X\n");
    printf ("X      HP-> O hp padrão das tropas são de        X\n");
    printf ("X       10 pontos de vida maxima.             o  X\n");
    printf ("X                                                X\n");
    printf ("X      Ataque-> O dano padrão das tropas é de    X\n");
    printf ("X       4 pontos de vida.                    O   X\n");
    printf ("X                              o                 X\n");
    printf ("X   O                 o            O           o X\n");
    printf ("X     o          O            Proxima Pagina-->  X\n");
    printf ("X                                            O   X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
			system("pause");
			system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X        O        | [Tutorial] |    o       o    X\n");
    printf ("X   o             |Jogabilidade|                 X\n");
    printf ("X      o          X------------X       O         X\n");
    printf ("X                                                X\n");
    printf ("X      Tipos de Guerreiro->                o     X\n");
    printf ("X      X-> Tropa padrão atira em linha reta      X\n");
    printf ("X O    S-> Tropa especial atira em linha reta    X\n");
    printf ("X      Y-> Tropa padrão atira em diagonal        X\n");
    printf ("X                                            O   X\n");
    printf ("X                    O          o                X\n");
    printf ("X   O         o                                o X\n");
    printf ("X                O            Proxima Pagina-->  X\n");
    printf ("X      o                o                    O   X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
			system("pause");
    		system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X        O        | [Tutorial] |            o    X\n");
    printf ("X   o             |Jogabilidade|     O           X\n");
    printf ("X      o       o  X------------X      o          X\n");
    printf ("X                                           o    X\n");
    printf ("X                 Ações no jogo                  X\n");
    printf ("X      Pode ser feito 3 ações por round do       X\n");
    printf ("X  O    jogador.                                 X\n");
    printf ("X                      O         o               X\n");
    printf ("X             o                              O   X\n");
    printf ("X                         o            o         X\n");
    printf ("X   O                                          o X\n");
    printf ("X        o       O            Proxima Pagina-->  X\n");
    printf ("X                                            O   X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
			system("pause");
    		system("cls");
}

void ComoJogar(){
	
	system("cls");
	printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X    O             |[Tutorial]|              O   X\n");
    printf ("X            o     |Como Jogar|      o           X\n");
    printf ("X   o              |----------|              o   X\n");
    printf ("X                                                X\n");
    printf ("X      ->O jogo se baseia em 2 campos com    o   X\n");
    printf ("X      9 guerreiros em cada lado, onde 1         X\n");
    printf ("X      deles possui uma habilidade especial.     X\n");
    printf ("X  o                                             X\n");
    printf ("X         o         O                     o      X\n");
    printf ("X                             o        O     o   X\n");
    printf ("X    O                                           X\n");
    printf ("X            o          O        o       O       X\n");
    printf ("X                                                X\n");
    printf ("X   o                  o      Proxima Pagina-->  X\n");
    printf ("X         O                                      X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    		system("pause");
    		system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X       o     O    |[Tutorial]|    o         O   X\n");
    printf ("X  O               |Como Jogar|                  X\n");
    printf ("X             o    |Mobilidade|      O    o      X\n");
    printf ("X    o                                           X\n");
    printf ("X      ->Para se mover no campo é necessario     X\n");
    printf ("X      quer o jogador utilize a caixa de texto   X\n");
    printf ("X O    escrevendo as respectivas letras para     X\n");
    printf ("X      os movimentos:                            X\n");
    printf ("X      W= Cima           o                   o   X\n");
    printf ("X      A= Esquerda                 O             X\n");
    printf ("X      S= Baixo       O         o                X\n");
    printf ("X      D= Direita                          O     X\n");
    printf ("X o                                              X\n");
    printf ("X          O          O       Proxima Pagina-->  X\n");
    printf ("X        o                                       X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    		system("pause");
    		system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X                o |[Tutorial]|    O       o     X\n");
    printf ("X     o            |Como Jogar|                  X\n");
    printf ("X          O       |---Tiro---|     o       O    X\n");
    printf ("X                                                X\n");
    printf ("X O    ->Para o uso dos tiros é utilizada        X\n");
    printf ("X      a opção 1)ataque, essa opção leva         X\n");
    printf ("X      o guerreiro atirar da determinada         X\n");
    printf ("X o    forma do guerreiro, caso seja guerreiro   X\n");
    printf ("X      \"X\", o tiro será em uma reta horizontal   X\n");
    printf ("X      caso seja o guerreiro \"Y\", terá a opção   X\n");
    printf ("X O    de direcionar para diagonal esquerda      X\n");
    printf ("X      ou diagonal direita.                    o X\n");
    printf ("X                                 o              X\n");
    printf ("X   o       O                 Proxima Pagina-->  X\n");
    printf ("X                  o     O                       X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    		system("pause");
    		system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X    O     o       |[Tutorial]|   o            O X\n");
    printf ("X              o   |Como Jogar|                  X\n");
    printf ("X    o             |--Magias--|      O           X\n");
    printf ("X             O               o             o    X\n");
    printf ("X                                                X\n");
    printf ("X o    ->Antes ao inicio dos jogos surge uma     X\n");
    printf ("X      seleção de megias, onde terá a possi-     X\n");
    printf ("X      bilidade de escolher 1 das 8 habilidades  X\n");
    printf ("X   o  disponiveis no jogo, a cada inicio de     X\n");
    printf ("X      uma nova partida haverá uma nova seleção  X\n");
    printf ("X      de magia.                                 X\n");
    printf ("X o                      O        o          O   X\n");
    printf ("X              o                                 X\n");
    printf ("X     O                  o    Proxima Pagina-->  X\n");
    printf ("X o                 O                            X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    		system("pause");
    		system("cls");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    printf ("X  o   O           |[Tutorial]|     o        o   X\n");
    printf ("X             O    |Como Jogar|          O       X\n");
    printf ("X O     o          |-Ganhador-|  O               X\n");
    printf ("X                                            o   X\n");
    printf ("X      ->Para definir um ganhador é necessa-     X\n");
    printf ("X  o   rio que elimine completamente os seus     X\n");
    printf ("X      inimigos. O jogador que conseguir         X\n");
    printf ("X      abater todos os inimigos permanecendo     X\n");
    printf ("X O    com pelo menos 1 guerreiro no campo       X\n");
    printf ("X      leva a vitoria!                           X\n");
    printf ("X                                   O         O  X\n");
    printf ("X o          o       BOM JOGO!            o      X\n");
    printf ("X     O               o          o               X\n");
    printf ("X                             Proxima Pagina-->  X\n");
    printf ("X       o          O                             X\n");
    printf ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\n");
    		system("pause");
    		system("cls");
}






